macOS 10.14 instead of 10.15
10.15 has breaking changes that are incompatible with Ice 3.6.5.
```
2020-03-11T18:13:02.7728430Z     In file included from src/ice/cpp/src/IceSSL/AcceptorI.cpp:14:
2020-03-11T18:13:02.7731970Z     In file included from src/ice/cpp/src/IceSSL/OpenSSLTransceiverI.h:14:
2020-03-11T18:13:02.7732870Z     In file included from src/ice/cpp/src/IceSSL/Util.h:23:
2020-03-11T18:13:02.7733730Z     In file included from /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:27:
2020-03-11T18:13:02.7739150Z     /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:91:33: error: typedef redefinition with different types ('struct __SecCertificate' vs 'OpaqueSecCertificateRef')
2020-03-11T18:13:02.7742840Z     typedef struct __SecCertificate OpaqueSecCertificateRef;
2020-03-11T18:13:02.7743540Z                                     ^
2020-03-11T18:13:02.7744230Z     src/ice/cpp/include/IceSSL/Plugin.h:67:8: note: previous definition is here
2020-03-11T18:13:02.7744760Z     struct OpaqueSecCertificateRef;
2020-03-11T18:13:02.7745320Z            ^
2020-03-11T18:13:02.7745790Z     In file included from src/ice/cpp/src/IceSSL/AcceptorI.cpp:14:
2020-03-11T18:13:02.7746580Z     In file included from src/ice/cpp/src/IceSSL/OpenSSLTransceiverI.h:14:
2020-03-11T18:13:02.7747400Z     In file included from src/ice/cpp/src/IceSSL/Util.h:23:
2020-03-11T18:13:02.7748240Z     In file included from /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:27:
2020-03-11T18:13:02.7750220Z     /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:114:25: error: typedef redefinition with different types ('struct __SecKey' vs 'OpaqueSecKeyRef')
2020-03-11T18:13:02.7751480Z     typedef struct __SecKey OpaqueSecKeyRef;
2020-03-11T18:13:02.7752100Z                             ^
2020-03-11T18:13:02.7752650Z     src/ice/cpp/include/IceSSL/Plugin.h:73:8: note: previous definition is here
2020-03-11T18:13:02.7753330Z     struct OpaqueSecKeyRef;
2020-03-11T18:13:02.7753700Z            ^
2020-03-11T18:13:03.1443150Z     2 errors generated.
```